import { DefaultTheme } from '@react-navigation/native';
import { Platform, StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#0A2540',
  accent: '#007BFF',
  background: '#F8F9FA',
  text: '#212529',
  subtleText: '#6c757d',
  success: '#28a745',
  error: '#E63946',
  card: '#FFFFFF',
  border: '#DEE2E6',
};

export const navTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: COLORS.primary,
    background: COLORS.background,
    card: COLORS.card,
    text: COLORS.text,
    border: COLORS.border,
    notification: COLORS.accent,
  },
};

export const SCANNER_BOX_SIZE = 250;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  authContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    paddingBottom: 50,
  },
  authTitle: {
    fontSize: 36,
    fontFamily: 'Roboto_700Bold',
    color: COLORS.primary,
    textAlign: 'center',
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 16,
    fontFamily: 'Roboto_400Regular',
    color: COLORS.subtleText,
    textAlign: 'center',
    marginBottom: 32,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  logoText: {
    fontSize: 48,
    fontFamily: 'Roboto_700Bold',
    color: COLORS.primary,
  },
  logoO: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 3,
    borderColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: -2,
  },
  logoOInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.primary,
  },
  linkText: {
    textAlign: 'center',
    color: COLORS.accent,
    fontFamily: 'Roboto_400Regular',
    fontSize: 15,
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.card,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 60,
  },
  headerSide: {
    flex: 1,
    flexDirection: 'row',
  },
  headerTitle: {
    flex: 2,
    fontSize: 18,
    color: COLORS.text,
    fontFamily: 'Roboto_700Bold',
    textAlign: 'center',
  },
  welcomeTitle: {
    fontSize: 28,
    fontFamily: 'Roboto_700Bold',
    color: COLORS.primary,
  },
  welcomeName: {
    fontSize: 18,
    fontFamily: 'Roboto_400Regular',
    color: COLORS.subtleText,
    marginBottom: 16,
  },
  welcomeText: {
    fontSize: 18,
    fontFamily: 'Roboto_400Regular',
    color: COLORS.text,
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'Roboto_400Regular',
    color: COLORS.subtleText,
  },
  countText: {
    fontSize: 28,
    fontFamily: 'Roboto_700Bold',
    color: COLORS.primary,
  },
  card: {
    backgroundColor: COLORS.card,
    marginHorizontal: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  label: {
    fontSize: 14,
    color: COLORS.subtleText,
    marginBottom: 8,
    fontFamily: 'Roboto_400Regular',
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    fontFamily: 'Roboto_400Regular',
    fontSize: 16,
    color: COLORS.text,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputDisabled: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    fontFamily: 'Roboto_400Regular',
    fontSize: 16,
    color: COLORS.subtleText,
    backgroundColor: COLORS.background,
  },
  primaryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Roboto_700Bold',
    fontSize: 16,
  },
  disabledButton: {
    opacity: 0.5,
  },
  outlineButton: {
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outlineButtonText: {
    color: COLORS.primary,
    fontFamily: 'Roboto_700Bold',
    fontSize: 16,
  },
  dangerButton: {
    backgroundColor: '#FFF1F2',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dangerButtonText: {
    color: COLORS.error,
    fontFamily: 'Roboto_700Bold',
    fontSize: 14,
  },
  paragraph: {
    color: COLORS.text,
    fontFamily: 'Roboto_400Regular',
    marginBottom: 16,
    lineHeight: 22,
  },
  cardTitle: {
    fontSize: 16,
    color: COLORS.text,
    fontFamily: 'Roboto_700Bold',
  },
  cardSubtitle: {
    fontSize: 14,
    color: COLORS.subtleText,
    marginTop: 4,
    fontFamily: 'Roboto_400Regular',
  },
  searchBar: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Roboto_400Regular',
    color: COLORS.text,
    marginLeft: 8,
    height: 50,
    fontSize: 16,
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    backgroundColor: COLORS.card,
    marginTop: -12,
    marginBottom: 16,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  scroll: {
    paddingBottom: 32,
  },
  emptyText: {
    fontFamily: 'Roboto_400Regular',
    color: COLORS.subtleText,
    fontSize: 16,
  },
  // Scanner styles
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unfocusedArea: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    width: '100%',
  },
  scannerFocusBox: {
    width: SCANNER_BOX_SIZE,
    height: SCANNER_BOX_SIZE,
    position: 'relative',
  },
  scannerCorner: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: 'white',
    borderWidth: 4,
  },
  topLeft: {
    top: -2,
    left: -2,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  topRight: {
    top: -2,
    right: -2,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  bottomLeft: {
    bottom: -2,
    left: -2,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  bottomRight: {
    bottom: -2,
    right: -2,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  scannerHelperText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Roboto_400Regular',
    textAlign: 'center',
  },
  scannerCloseButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 40 : 60,
    left: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
});